apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: dataops-bootcamp-postgresql
  namespace: dataops-api
spec:
  allowedSourceRanges:
  - 0.0.0.0/0
  teamId: "dataops"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    dataops:  # database owner
    - superuser
    - createdb
    learner_user: []  # role for application foo
  databases:
    learner: dataops  # dbname: owner
  postgresql:
    version: "12"
