apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dataops-api
commonLabels:
    app.kubernetes.io/name: dataops-api
    app.kubernetes.io/component: webapi
    app.kubernetes.io/framework: flask
    app.kubernetes.io/version: "0.0.1-SNAPSHOT"
    app.kubernetes.io/part-of: animal-rescue

resources:
- deployment.yaml
- service.yaml
- namespace.yaml
- ingress.yaml
- db.yaml
